# Define the goal
uint32 startmode
float32 length
geometry_msgs/Pose2D pose
---
# Define the result
uint32 result
uint32 last_step
uint32 error_code
---
# Define a feedback message
uint32 step
float32 voltage
float32 current
uint32 reflector_intensity
geometry_msgs/Pose poseonreflector
